"use client";
import * as React from "react";

/*
  The runtime half of the Liquid Glass material. Three jobs, one component,
  mounted once in the app shell.

  1. It defines the SVG displacement filter that does the actual refraction.
  2. It decides whether this engine can run that filter, and says so on <html>.
  3. It moves the light source with the pointer.

  Everything else about the material is CSS. This exists because none of these
  three can be expressed in a stylesheet.
*/

/*
  The lens.

  feImage loads the displacement map — a rounded-rectangle bevel generated by
  scripts/gen-lens-map.ts, where red carries the horizontal offset, green the
  vertical, and 128 means "leave this pixel alone". feDisplacementMap then
  pushes the backdrop around by what it reads there, so the rim bends and the
  middle stays flat. That is the whole trick, and it is what separates glass
  from frost.

  color-interpolation-filters="sRGB" is load-bearing. The SVG default is
  linearRGB, which would gamma-convert the map before reading it, moving the
  128 neutral off-centre and leaving the middle of every pane quietly smeared.

  preserveAspectRatio="none" lets one square map stretch to a tall rail or a
  wide toolbar. The bevel distorts with it, which is correct — a wider pane has
  a wider bevel.
*/
function LensFilter() {
  return (
    <svg
      aria-hidden
      focusable="false"
      // Not display:none: a filter inside a display:none subtree is not
      // resolvable as a url() reference in some engines, and the panes it
      // feeds silently lose their blur with it. Zero-sized and out of flow
      // keeps it referenceable and costs no layout.
      style={{ position: "absolute", width: 0, height: 0, overflow: "hidden", pointerEvents: "none" }}
    >
      <defs>
        <filter
          id="lg-lens"
          x="0%"
          y="0%"
          width="100%"
          height="100%"
          colorInterpolationFilters="sRGB"
        >
          <feImage
            href="/lens-map.png"
            result="map"
            preserveAspectRatio="none"
            x="0%"
            y="0%"
            width="100%"
            height="100%"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="map"
            scale="22"
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
      </defs>
    </svg>
  );
}

export function LiquidGlass() {
  React.useEffect(() => {
    const root = document.documentElement;

    /*
      Can this engine apply an SVG filter to a backdrop?

      This has to be answered by engine, not by CSS.supports, and that is a
      genuinely unpleasant thing to have to write.

      An SVG filter inside backdrop-filter is outside the CSS spec and only
      Chromium renders it. Firefox parses the declaration, answers true to
      CSS.supports, and then paints nothing — which would not merely cost us
      the refraction, it would cost the blur and the saturation in the same
      declaration and leave a flat tinted rectangle where the material should
      be. Safari drops it too. So a capability query is exactly the wrong tool
      here: the thing it reports is not the thing we need to know.

      userAgentData.brands is the narrow, honest version of the question —
      which engine is this — and it degrades to the UA string on engines that
      do not implement it. Wrong answers are safe in one direction only, so
      the test is written to require positive evidence of Chromium rather than
      to rule out the others.
    */
    const brands: { brand: string }[] =
      (navigator as unknown as { userAgentData?: { brands?: { brand: string }[] } })
        .userAgentData?.brands ?? [];
    const isChromium = brands.length
      ? brands.some((b) => b.brand === "Chromium")
      : / Chrome\/\d/.test(navigator.userAgent) && !/ (Edg|OPR)\//.test(navigator.userAgent);

    const parses =
      typeof CSS !== "undefined" &&
      typeof CSS.supports === "function" &&
      CSS.supports("backdrop-filter", "url(#lg-lens)");

    if (isChromium && parses) root.classList.add("lg-probe-ok");

    /*
      The light.

      One source for the whole page, written to the root as a pair of 0..1
      numbers that every rim reads. Physically that is right — a room has one
      window — and practically it is the only affordable shape: a listener per
      glass element would be dozens of them, each invalidating its own rim on
      every mouse move.

      Throttled to a frame. pointermove fires far faster than the compositor
      can use, and writing a custom property is a style invalidation; unthrottled
      it is the most expensive thing on the page for no visible gain.
    */
    let frame = 0;
    let px = 0.5;
    let py = 0;

    const commit = () => {
      frame = 0;
      root.style.setProperty("--lg-px", String(px));
      root.style.setProperty("--lg-py", String(py));
    };

    const onMove = (e: PointerEvent) => {
      px = Math.min(1, Math.max(0, e.clientX / window.innerWidth));
      py = Math.min(1, Math.max(0, e.clientY / window.innerHeight));
      if (!frame) frame = requestAnimationFrame(commit);
    };

    /*
      Only where there is a pointer to follow. On a touch screen there is no
      hover position between taps, so the highlight would sit wherever the last
      tap left it — a bright spot frozen in a corner, which reads as a defect.
      Touch keeps the default: light from above, the way a screen in a hand is
      actually lit.
    */
    const fine = window.matchMedia("(pointer: fine)");
    if (fine.matches) {
      window.addEventListener("pointermove", onMove, { passive: true });
    }

    return () => {
      window.removeEventListener("pointermove", onMove);
      if (frame) cancelAnimationFrame(frame);
    };
  }, []);

  return <LensFilter />;
}
